fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: make-pre-commit
        name: 'make pre commit'
        entry: make precommit
        language: 'system'
        pass_filenames: false
        verbose: true
