fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: local
    hooks:
      # - id: toolkit
      #   name: toolkit
      #   entry: go install github.com/machinefi/w3bstream/pkg/depends/gen/cmd/...@toolkit-patch-0.0.3
      #   language: golang
      - id: make_pre_commit
        name: make_pre_commit
        entry: make precommit
        language: golang
