GO_RUNTIME_ENV: DEV
SRV_APPLET_MGR__BROKER__Keepalive: 3h
SRV_APPLET_MGR__BROKER__QoS: ONCE
SRV_APPLET_MGR__BROKER__RetainPublish: "false"
SRV_APPLET_MGR__BROKER__Retry_Interval: 3s
SRV_APPLET_MGR__BROKER__Retry_Repeats: "3"
SRV_APPLET_MGR__BROKER__Server: mqtt://127.0.0.1:1883
SRV_APPLET_MGR__BROKER__Timeout: 3s
SRV_APPLET_MGR__ETHCLIENTCONFIG__ChainEndpoint: ""
SRV_APPLET_MGR__ETHCLIENTCONFIG__PrivateKey: ""
SRV_APPLET_MGR__JWT__ExpIn: 0s
SRV_APPLET_MGR__JWT__Issuer: ""
SRV_APPLET_MGR__JWT__SignKey: ""
SRV_APPLET_MGR__LOG__Format: JSON
SRV_APPLET_MGR__LOG__Level: debug
SRV_APPLET_MGR__LOG__Name: srv-applet-mgr
SRV_APPLET_MGR__LOG__Output: ALWAYS
SRV_APPLET_MGR__LOG__ReportCaller: "false"
SRV_APPLET_MGR__PGCLI__ConnMaxLifetime: 1h
SRV_APPLET_MGR__PGCLI__Master: postgres://127.0.0.1:5432
SRV_APPLET_MGR__PGCLI__PoolSize: "10"
SRV_APPLET_MGR__PGCLI__Retry_Interval: 3s
SRV_APPLET_MGR__PGCLI__Retry_Repeats: "3"
SRV_APPLET_MGR__PGCLI__Slave: ""
SRV_APPLET_MGR__REDIS__ConnectTimeout: 10s
SRV_APPLET_MGR__REDIS__DB: "1"
SRV_APPLET_MGR__REDIS__Host: 127.0.0.1
SRV_APPLET_MGR__REDIS__IdleTimeout: 4m
SRV_APPLET_MGR__REDIS__MaxActive: "5"
SRV_APPLET_MGR__REDIS__MaxIdle: "3"
SRV_APPLET_MGR__REDIS__Password: ""
SRV_APPLET_MGR__REDIS__Port: "6379"
SRV_APPLET_MGR__REDIS__Prefix: 'dev:srv-applet-mgr@0.0.1:'
SRV_APPLET_MGR__REDIS__Protocol: tcp
SRV_APPLET_MGR__REDIS__ReadTimeout: 10s
SRV_APPLET_MGR__REDIS__Wait: "true"
SRV_APPLET_MGR__REDIS__WriteTimeout: 10s
SRV_APPLET_MGR__SERVER__Debug: "true"
SRV_APPLET_MGR__SERVER__HealthCheck: http://:80/
SRV_APPLET_MGR__SERVER__Port: "80"
SRV_APPLET_MGR__SERVER__Spec: ./swagger.json
SRV_APPLET_MGR__UPLOADCONFIG__FileSizeLimit: "104857600"
SRV_APPLET_MGR__UPLOADCONFIG__Root: ./asserts
