@startuml

hide footbox
title: Project/Applet/Instance Management

actor       "user"          as cli
participant "bff"           as bff
participant "gateway"       as gw
participant "mqtt"          as mqtt
participant "core"          as core

ref over gw
gateway is unified device gateway, which
supports device management and multi transporter
for event entrance
end ref

== Register Device API ==

cli  -> bff:  POST /device\n{token + project name + device info}
bff  -> gw:   POST /device\n{account id + project name + device info}

group MQTT entrance Authorization (optional)
gw   -> mqtt: /v2/project/{project_id}/mqttuser {Creating MQTT user}
mqtt -> gw:   MQTT user info{transporter certification}
end

group HTTP project validation (required)
gw   -> core: GET /project\n{account id + project name}
core -> core: validate project permission
core -> gw:   {account info + project info}
end

gw   -> gw:   create device
gw   -> bff:  device info + pub token + transporter certification(optional)
bff  -> cli:  device info + pub token + transporter certification(optional)

== Event Receiving ==

ref over cli
event body: {event_id, device_id, pub_time, event_type, pub_token}
end ref
cli  -> bff:  POST /event\n{pub token + event body}
bff  -> gw:   POST /event\n{pub id + event body}
gw   -> core: POST /event\n{pub id + project id + event body}
core -> core: event routing by strategy
core -> gw:   event response

== Device Self Register through DID @TODO @Zhiran ==

@enduml