version: '3'
services:
  redis:
    image: 'redis:6.0'
    restart: always
    container_name: redis
    volumes:
      - ../build/var/redis/data:/data
      - ../build/var/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ../build/var/redis/logs:/logs
    command:
      redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'