name: ci_docker_hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
          go-version: 1.19.x
                
    - shell: bash
      run: |
        ls
        ls frontend/
        go mod tidy
        go mod vendor
        git submodule update --init
        cd frontend &&	git pull origin main
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/w3bstream:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/w3bstream:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/w3bstream:buildcache,mode=max
